### ISSUE TITLE
UI Alignment

### ISSUE THREAD

**Issue by KipCrossing** [OpenGovAus/ausbills#34]
We need to get some UI alignment between all the parliament scrapers. We should have a workshop for this.

### Common names
We should try and get common names between all on them. For example, Senate vs LA; we could just use Upper

### Common Objects
We already use **Bill** but should do more. Max has some more in the WA scraper

### Common Errors

This will help the user to debug and handle errors in their own way

### Typing
We should def use more typing to help the user. Common classes will help with this

Note, I'm not loving the fact that the user has to use the `.value` property with Maybe Just/Nothing (pymonad). We should abstract this away from the user when possible. ie `return(result.value)`

**Comment by king-millez** [comment]
Agreed, before we add anymore parliaments, we should get this stuff sorted.

**Comment by KipCrossing** [comment]
The WA UI is like this:

```python
# get a list of these BillProgress dataclass
bills_progs = scrape_all_bill_progs()

# feed that list into scrape_all_bills
results = scrape_all_bills(bills_progs=bills_progs)
# returns a tuple of BillProgress and Bill

for (bp, bill_e) in results:
    bp: BillProgress
    b: Bill = bill_e.value #value because bill_e is an Either
    print(b.name)
```

and as it is, it differs from all the other UI's. Not wrong or bad, just need alignment.

**Comment by king-millez** [comment]
I've also been using `[state]_All_Bills` and `[state]_Bill` for my object names, getting it all consistent with the other states will be helpful.

**Comment by KipCrossing** [comment]
Instead of using `[state]_All_Bills`, let's use something more basic than Bill. I like the idea of `scrape_all_bill_progs` from WA but it may not apply to all parliments. 

Perhaps somthing like `get_bills_metadata()` that returns List[BillMeta]. BillMeta would be a dataclass with at least `id` and `link` in it.

**Comment by KipCrossing** [comment]
Also, need to discuss if `scrape_all_bills()` should be within the scope of ausbills

**Comment by KipCrossing** [comment]
Errors should include:
- MetaScrapsError
- BillScrapsError

**Comment by KipCrossing** [comment]
I also think we should give the user one date string format and they can figure it out. perhaps a list ie: `[10,4,2020]`

**Comment by KipCrossing** [comment]
Some potential inspiration for var names:

https://theyvoteforyou.org.au/help/data

**Comment by connorhsm** [comment]
@KipCrossing @king-millez Can we spend 30 minutes max creating a doc on the agreed common names, objects and errors, sometime this week?
I'll then make this into a project and issues and we can go from there.

**Comment by king-millez** [comment]
#54
