### ISSUE TITLE
Irrelevant TAS topic

### ISSUE THREAD

**Issue by Makonede** [OpenGovAus/ausbills#56]
The TAS topic is meant for tool-assisted speedrunning, not Tasmania. This tag should be removed from this repository.

**Comment by KipCrossing** [comment]
This reop is no longer actively maintained. Please make a Pull Request with the suggested changes.

**Comment by XertroV** [comment]
@Makonede, while I sympathize (I moderate speedrun.com/ssol), wrgaf considering. see https://voteflux.org/2022/04/20/wrongful-deregistration/ (this project, via it's contributors, was somewhat affiliated with the linked org)

**Comment by Makonede** [comment]
@KipCrossing Tags aren't files, they're GitHub specific. Pull requests can't change tags.

**Comment by KipCrossing** [comment]
> @KipCrossing Tags aren't files, they're GitHub specific. Pull requests can't change tags.

In order to change the setting on the repo, you must be an active maintainer of the project. Please see the [CONTRIBUTING](https://github.com/OpenGovAus/ausbills/blob/master/CONTRIBUTING.md) doc.
